language: php
php:
  - nightly
  - "8.0"
  - "7.3"

services:
  - docker

install:
  - docker-compose up -d
  - composer install

script: 
  - vendor/bin/phpunit
    
jobs:
  include:
    - stage: documentation
      if: branch = master
      install: skip
      script: "curl https://opensource.byjg.com/add-doc.sh | bash /dev/stdin php webrequest"


